CREATE TABLE [dbo].[Address] (
    [Id]              INT        IDENTITY (1, 1) NOT NULL,
    [ProfileId]       INT        NOT NULL,
    [Address1]        NVARCHAR(MAX) NULL,
    [Address2]        NVARCHAR(MAX) NULL,
    [Landmark]        NVARCHAR(MAX) NULL,
    [CityId]          INT NULL,
    [StateId]         INT NULL,
    [CountryId]       INT NULL,
    [PinNo]           NVARCHAR(MAX) NULL,
    [TypeId]          INT NULL,
    [DisplayOrder]    INT        NULL,
    [CreatedBy]       INT        NULL,
    [CreatedDateTime] DATETIME   NULL,
    [UpdatedBy]       INT        NULL,
    [UpdatedDateTime] DATETIME   NULL,
    [IsDeleted]       BIT        NULL,
    CONSTRAINT [PK_Address] PRIMARY KEY CLUSTERED ([Id] ASC),
    CONSTRAINT [FK_Address_AspNetUsers] FOREIGN KEY ([CreatedBy]) REFERENCES [dbo].[AspNetUsers] ([Id]),
    CONSTRAINT [FK_Address_AspNetUsers1] FOREIGN KEY ([UpdatedBy]) REFERENCES [dbo].[AspNetUsers] ([Id]),
    CONSTRAINT [FK_Address_Profile] FOREIGN KEY ([ProfileId]) REFERENCES [dbo].[Profile] ([Id]),
    CONSTRAINT [FK_Address_CountryID] FOREIGN KEY ([CountryId]) REFERENCES [dbo].[Country] ([Id]),
    CONSTRAINT [FK_Address_StateID] FOREIGN KEY ([StateId]) REFERENCES [dbo].[State] ([Id]),
    CONSTRAINT [FK_Address_CityID] FOREIGN KEY ([CityId]) REFERENCES [dbo].[City] ([Id])
);

